import React, { useState, useRef, useEffect } from 'react';
import type { Ingredient, Recipe } from './types';
import Header from './components/Header';
import Pantry from './components/Pantry';
import RecipeList from './components/RecipeList';
import Footer from './components/Footer';
import { db } from './firebase';
import { collection, onSnapshot, addDoc, doc, updateDoc, deleteDoc } from 'firebase/firestore';
import RecipeModal from './components/RecipeModal';

const RECIPES_PER_PAGE = 6;

const App: React.FC = () => {
    const [ingredients, setIngredients] = useState<Ingredient[]>([]);
    const [recipes, setRecipes] = useState<Recipe[]>([]);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [isLoadingMore, setIsLoadingMore] = useState<boolean>(false);
    const [hasMore, setHasMore] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);
    const [language, setLanguage] = useState<string>('English');
    const [selectedRecipe, setSelectedRecipe] = useState<Recipe | null>(null);
    const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
    const [videoUrl, setVideoUrl] = useState<string | null>(null);
    const currentQueryRef = useRef<string>('');

    useEffect(() => {
        const unsubscribe = onSnapshot(collection(db, "ingredients"), (snapshot) => {
            const ingredientsData = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })) as Ingredient[];
            setIngredients(ingredientsData);
        });
        return () => unsubscribe();
    }, []);

    const handleLanguageChange = (lang: string) => {
        setLanguage(lang);
    };

    const handleRecipeSelect = (recipe: Recipe) => {
        setSelectedRecipe(recipe);
        setIsModalOpen(true);
    };

    const handleCloseModal = () => {
        setIsModalOpen(false);
        setSelectedRecipe(null);
        setVideoUrl(null); // Clear video when modal closes
    };



    const fetchRecipesFromAPI = async (query: string, isLoadMore: boolean = false) => {
        const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
        if (!apiKey) {
            throw new Error("GEMINI_API_KEY is not set in the environment variables.");
        }

        const pantryList = ingredients.map(i => i.name);
        const prompt = `
            You are a recipe assistant. Your task is to find 6 diverse recipes based on the user's pantry.
            The user has the following ingredients: ${pantryList.join(', ')}.
            
            Please provide the response in ${language}.

            Your response MUST be a single, valid JSON array of recipe objects, enclosed in a JSON markdown block.
            Each recipe object must have:
            {
              "title": "Recipe Title",
              "description": "Short description",
              "cuisine": "Cuisine type",
              "cookTime": 60,
              "ingredients": [
                { "name": "Ingredient Name", "quantity": "Quantity", "inPantry": true/false }
              ],
              "instructions": ["Step 1", "Step 2"]
            }
        `;

        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: prompt }]
                }]
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Gemini API Error: ${response.status} - ${errorText}`);
        }

        const result = await response.json();
        const text = result.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!text) {
            console.error("No text in Gemini response");
            throw new Error("No content generated by AI.");
        }

        // Extract JSON from code blocks or direct JSON
        let jsonText = "";

        // Try JSON markdown block first
        const jsonBlockMatch = text.match(/```json\s*([\s\S]*?)\s*```/);
        if (jsonBlockMatch) {
            jsonText = jsonBlockMatch[1];
        } else {
            // Try plain code block
            const codeBlockMatch = text.match(/```\s*([\s\S]*?)\s*```/);
            if (codeBlockMatch) {
                jsonText = codeBlockMatch[1];
            } else {
                // Try direct JSON array
                const arrayMatch = text.match(/\[\s*\{[\s\S]*\}\s*\]/);
                if (arrayMatch) {
                    jsonText = arrayMatch[0];
                }
            }
        }

        if (!jsonText) {
            console.error("Could not extract JSON. Full response:", text.substring(0, 1000));
            throw new Error("Could not find JSON in AI response. See console for details.");
        }

        let recipeData;
        try {
            recipeData = JSON.parse(jsonText);
        } catch (parseError) {
            console.error("JSON parse error:", parseError);
            console.error("Attempted to parse:", jsonText.substring(0, 500));
            throw new Error("Failed to parse recipe JSON from AI response.");
        }

        if (!Array.isArray(recipeData)) {
            console.error("Parsed data is not an array:", recipeData);
            throw new Error("AI response is not a valid recipe array.");
        }

        const sources: { uri: string; title: string }[] = [];
        return recipeData.map((r: Omit<Recipe, 'sources'>) => ({ ...r, sources }));
    };

    const findRecipes = async (searchQuery?: string) => {
        const pantryList = ingredients.map(i => i.name.toLowerCase());
        if (!searchQuery && pantryList.length === 0) {
            setError("Your pantry is empty. Add ingredients or use the search bar to find recipes.");
            return;
        }

        setIsLoading(true);
        setError(null);
        setRecipes([]);
        setHasMore(false);

        const query = searchQuery || `recipes I can make with: ${ingredients.map(i => i.name).join(', ')}`;
        currentQueryRef.current = query;

        try {
            const newRecipes = await fetchRecipesFromAPI(query);
            setRecipes(newRecipes);
            setHasMore(newRecipes.length === RECIPES_PER_PAGE);
        } catch (err) {
            console.error("Error fetching recipes:", err);
            const errorMessage = err instanceof Error ? err.message : "An unknown error occurred.";
            setError(`Sorry, I couldn't find recipes at the moment. Please try again later. Details: ${errorMessage}`);
        } finally {
            setIsLoading(false);
        }
    };

    const loadMoreRecipes = async () => {
        if (isLoading || isLoadingMore || !hasMore) return;

        setIsLoadingMore(true);
        setError(null);

        try {
            const newRecipes = await fetchRecipesFromAPI(currentQueryRef.current, true);
            setRecipes(prev => [...prev, ...newRecipes]);
            setHasMore(newRecipes.length === RECIPES_PER_PAGE);
        } catch (err) {
            console.error("Error fetching more recipes:", err);
            const errorMessage = err instanceof Error ? err.message : "An unknown error occurred.";
            setError(`Could not load more recipes. Please try again. Details: ${errorMessage}`);
        } finally {
            setIsLoadingMore(false);
        }
    };

    const addIngredient = async (ingredient: Omit<Ingredient, 'id'>) => {
        await addDoc(collection(db, "ingredients"), ingredient);
    };

    const removeIngredient = async (id: string) => {
        await deleteDoc(doc(db, "ingredients", id));
    };

    const updateIngredient = async (updatedIngredient: Ingredient) => {
        const { id, ...data } = updatedIngredient;
        await updateDoc(doc(db, "ingredients", id), data);
    };

    return (
        <div className="min-h-screen bg-brand-gray font-sans text-gray-800">
            <Header language={language} onLanguageChange={handleLanguageChange} />
            <main className="container mx-auto p-4 lg:p-8">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                    <div className="lg:col-span-5 xl:col-span-4">
                        <Pantry
                            ingredients={ingredients}
                            onAdd={addIngredient}
                            onRemove={removeIngredient}
                            onUpdate={updateIngredient}
                            onFindRecipes={() => findRecipes()}
                            isLoading={isLoading}
                        />
                    </div>
                    <div className="lg:col-span-7 xl:col-span-8">
                        <RecipeList
                            recipes={recipes}
                            isLoading={isLoading}
                            isLoadingMore={isLoadingMore}
                            hasMore={hasMore}
                            error={error}
                            onSearch={findRecipes}
                            onLoadMore={loadMoreRecipes}
                            onRecipeSelect={handleRecipeSelect}
                        />
                    </div>
                </div>
            </main>
            <Footer />
            {isModalOpen && <RecipeModal recipe={selectedRecipe} onClose={handleCloseModal} videoUrl={videoUrl} />}
        </div>
    );
};

export default App;